apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 80         # Service Port
      targetPort: 5000  # Port on the Pod
      nodePort: 30001   # Exposed NodePort
  type: NodePort


