apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddev
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: chizzy1234/backend
        ports:
        - containerPort: 5000
