name: Flask + React CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Flask Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-backend

    
